### ISSUE TITLE
wee_reports crashes with "TypeError: '>' not supported between instances of 'NoneType' and 'float'" (fixed)

### ISSUE THREAD

**Issue by g6g8** [gjr80/weewx-highcharts#10]
When running wee_reports I get this error:
(This is with latest "official" release, ie 0.3.0):

```
$ wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 149, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 308, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 379, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/highchartssearchlist.py", line 1243, in get_extension_list
    period)
  File "/usr/share/weewx/user/highchartssearchlist.py", line 961, in calc_windrose
    max_speed = max(speed_vec_vt.value)
TypeError: '>' not supported between instances of 'NoneType' and 'float'
$
```

After fixing this on my own I noticed this has already been officially fixed.
Gary, would you agree to release 0.3.1 please ? so we can just download it as latest and not run into this "bug".
Many thanks in advance.
Gabriel.

**Comment by gjr80** [comment]
Unfortunately v0.3.1 was written but never released. Fix is in v0.3.2.
