### ISSUE TITLE
wee_extension --install fails

### ISSUE THREAD

**Issue by g6g8** [gjr80/weewx-highcharts#9]
If I retrieve the latest weewx-highcharts (for python3) as follows:
`wget https://github.com/gjr80/weewx-highcharts/archive/python3.zip -O /tmp/hfw.zip`

Then install with wee_extension as follows:
`wee_extension --install=/tmp/hfw.zip`
I get the following error:
```
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 123, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 181, in install_from_dir
    shutil.copy(source_path, destination_path)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/weewx-highcharts-python3/bin/user/highchartsSearchX.py'
```

To fix I changed in file install.py, line 171 to read as follows:
`files=[('bin/user', ['bin/user/highchartssearchlist.py']`

**Comment by gjr80** [comment]
Thanks but the python3 branch is used for development and you pull from it at your peril. Releases are published on the releases tab as per the readme. Whilst the python3 code may work it is still to be tested. As advised in [this thread](https://groups.google.com/g/weewx-user/c/bs6U9s-BtDI) I will post when a python3 compatible version is released.
